# Use Python 3.9 as base image
FROM python:3.9

# Set working directory inside the container
WORKDIR /app

# Copy project files
COPY . .

# Copy the torch_wheels directory from location
COPY ../torch_wheels /tmp/torch_wheels

# Install torch wheels
RUN pip install --no-cache-dir /tmp/torch_wheels/*

# Install other dependencies
RUN pip install --no-cache-dir -r project/requirements.txt

# Expose port for FastAPI
EXPOSE 7860

# Start the application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]
