# Use an official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the main project files
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r  project/requirements.txt

# Copy the entire project into the container
COPY . .

# Expose the FastAPI default port
EXPOSE 8000

# Command to start FastAPI with Uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
